pipeline:
  install:
    image: node:carbon
    commands:
      - npm install --quiet
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  lint:
    image: node:carbon
    commands:
      - npm run lint
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/ui-example:
    image: node:carbon
    environment:
      - NODE_ENV=production
    commands:
      - npm run dist
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/ui-lib:
    image: node:carbon
    environment:
      - NODE_ENV=production
    commands:
      - npm run lib
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  deploy:
    image: node:carbon
    secrets: [ SSH_HOST, SSH_KEY, SSH_PATH ]
    commands:
      - npm install -g gulp
      - gulp deploy:production
    when:
      branch:
        - master
      event:
        - push

  publish:
    image: plugins/npm
    secrets: [ NPM_TOKEN, NPM_EMAIL ]
    when:
      branch:
        - master
      event:
        - push
