pipeline:
  lint:
    image: node:carbon
    commands:
      - npm install --quiet
      - npm run eslint
      - npm run stylint
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build_production:
    image: node:carbon
    environment:
      - NODE_ENV=production
    secrets: [ root_key ]
    commands:
      - npm run dist
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  deploy_production:
    image: node:carbon
    secrets: [ root_key ]
    commands:
      - npm run deploy:production
    when:
      branch:
        - master
      event:
        - push
