pipeline:
  test:
    image: node:8
    commands:
      - npm install --quiet
      - npm run eslint
      - npm run stylint
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build:
    image: node:carbon
    commands:
      - npm install --quiet
      - npm run dist

    when:
      branch:
        - master
      event:
        - push
        - pull_request
