pipeline:
  install:
    image: node:carbon
    commands:
      - npm install --quiet
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  lint:
    image: node:carbon
    commands:
      - npm run eslint
      - npm run stylint
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build_production_example:
    image: node:carbon
    environment:
      - NODE_ENV=production
    secrets: [ root_key ]
    commands:
      - npm run dist
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build_package:
    image: node:carbon
    environment:
      - NODE_ENV=production
    commands:
      - npm run lib
    when:
      branch:
        - master
      event:
        - push

  deploy_production_example:
    image: node:carbon
    secrets: [ root_key ]
    commands:
      - npm install -g gulp
      - gulp deploy:production
    when:
      branch:
        - master
      event:
        - push

  deploy_package:
    image: plugins/npm
    username: iknpx@aol.com
    email: iknpx@aol.com
    registry: https://registry.npmjs.org/
    secrets: [ npm_password ]
    when:
      branch:
        - master
      event:
        - push
