pipeline:
  install:
    image: node-yarn:latest
    commands:
      - yarn
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  lint:
    image: node-yarn:latest
    commands:
      - yarn lint
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/examples:
    image: node-yarn:latest
    environment:
      - NODE_ENV=production
    commands:
      - yarn dist
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  build/library:
    image: node-yarn:latest
    environment:
      - NODE_ENV=production
    commands:
      - yarn lib
    when:
      branch:
        - master
        - feature/*
      event:
        - push
        - pull_request

  deploy/examples:
    image: node-yarn:latest
    secrets: [ SSH_HOST, SSH_KEY, SSH_PATH ]
    commands:
      - npm install -g gulp
      - gulp deploy:production
    when:
      branch:
        - master
      event:
        - push

  publish/library:
    image: plugins/npm
    secrets: [ NPM_TOKEN, NPM_EMAIL ]
    when:
      branch:
        - master
      event:
        - push
