pipeline:
  test:
    image: node:carbon
    commands:
      - npm install --quiet
      - npm run eslint
      - npm run stylint
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build:
    image: node:carbon
    environment:
      - NODE_ENV=production
    commands:
      - npm run dist
      - npm run deploy

    when:
      branch:
        - master
      event:
        - push
        - pull_request
