pipeline:
  lint:
    image: node:carbon
    commands:
      - npm install --quiet
      - npm run eslint
      - npm run stylint
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  build_production:
    image: node:carbon
    environment:
      - NODE_ENV=production
    secrets: [ root_key ]
    commands:
      - npm run dist
    when:
      branch:
        - master
      event:
        - push
        - pull_request

  deploy_production:
    image: node:carbon
    secrets: [ root_key ]
    commands:
      - npm install -g gulp
      - gulp deploy:production
    when:
      branch:
        - master
      event:
        - push

  build_package:
    image: node:carbon
    environment:
      - NODE_ENV=production
    commands:
      - npm run lib
    when:
      branch:
        - master
      event:
        - push

  npm:
    image: plugins/npm
    username: iknpx@aol.com
    email: iknpx@aol.com
    secrets: [ npm_password ]
    when:
      branch:
        - master
      event:
        - push
