---
parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - jest-enzyme

plugins:
  - import
  - jsx-a11y
  - react
  - jest

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true

settings:
  import/resolver:
    node:
      moduleDirectory: ['node_modules', './src']
    webpack:
      config: './webpack/index.js'

rules:
  comma-dangle: [2, always-multiline]
  indent: [2, 4]
  jsx-a11y/click-events-have-key-events: [0]
  jsx-a11y/label-has-for: [0]
  jsx-a11y/no-static-element-interactions: [0]
  linebreak-style: [2, unix]
  no-tabs: [2]
  react/jsx-indent-props: [2, 4]
  react/jsx-indent: [2, 4]
  react/prop-types: [2, ignore: [children]]
  semi: [2, always]
